services:
  external-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      APP_PORT: ${APP_PORT}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      SCRAPER_ADDRESS: ${SCRAPER_ADDRESS}
      LOGURU_LEVEL: ${LOGURU_LEVEL}
    depends_on:
      - db
